### ISSUE TITLE
Make Single User or Unique

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes_manual#21]
In my LIVE NODING exploration of AN, especially on Alembic and Particle System, I realized that sometimes Instance Copy does not go deep enough to make Object Particle System and Materials become "unique" per Object Copy.

Is there a way around or tips for this using Python?

"Make Single User" command does not always work somewhat.

Thanks!

**Comment by hapit** [comment]
Is this issue still valid?
If so please create an issue at the addons github project: https://github.com/JacquesLucke/animation_nodes/issues/new

This project is for the animation nodes addon **manual** only!
Please post only issues with the manual here.

I will close the issue because it belongs to the addon project.
