### ISSUE TITLE
Subprogram: Find Max Integer (Example 10)

### ISSUE THREAD

**Issue by RodeyOrg** [JacquesLucke/animation_nodes_manual#49]
https://github.com/JacquesLucke/animation_nodes_manual/blob/master/docs/user_guide/subprograms/loop.rst

Can someone please help me understand this subprogram. The part I had been stuck on is how the Integer List of parameters is compared with the output from the Get List Element.

My understanding is that it works something like this

1. Firstly the output of the integer list is fed into the loop
2. Then the elements from the get list element are individually compared against the whole(?) list ?

What I don't understand is how the individual elements (from Get Elements List outout) are compared to the larger integer list. **Can someone please break this down for me  in some detail but simply.**

![loop_example10](https://user-images.githubusercontent.com/44178760/47272738-e4beb100-d581-11e8-8e60-f026e1ed590c.png)

**Comment by OmarSquircleArt** [comment]
You are not comparing the list and the value. Basically, when a list is used as an iterator, the list feeds the loop its nth element at the nth iteration. So:

1. At the first iteration, the list feeds the loop the first integer `1`, it checks if it is bigger than the Max which is `1`, since it isn't, nothing happens.
2. At the second iteration, the list feeds the loop the second integer `28`, it checks if it is bigger than the Max which is `1`, since it is, it reassign the Max to the integer `28`.
3. At the third iteration, the list feeds the loop the third integer `34`, it checks if it is bigger than the Max which is `28`, since it is, it reassign the Max to the integer `34`.
4. At the fourth iteration, the list feeds the loop the fourth integer `17`, it checks if it is bigger than the Max which is `34`, since it isn't, nothing happens.
5. At the last iteration, the list feeds the loop the last integer `65`, it checks if it is bigger than the Max which is `34`, since it is, it reassign the Max to the integer `65`.

When the parameter Max is output (Check the Parameters Sockets section of the documentation), it carries the value `65`, which is the greatest value in the list. Does it make sense now?

**Comment by RodeyOrg** [comment]
That's great, thank you. 

After days on this, any chance of being able to identifying what is wrong here by a screenshot? My output is stuck, _i.e. doesn't change value._
 
OSX 10 + Blender 2.79 + AN 2.0.4

<img width="1239" alt="screen shot 2018-10-22 at 23 13 11" src="https://user-images.githubusercontent.com/44178760/47322525-2fa6fa00-d650-11e8-9a01-21770a574de4.png">
