### ISSUE TITLE
Data Copying & Append List Example

### ISSUE THREAD

**Issue by RodeyOrg** [JacquesLucke/animation_nodes_manual#51]
Hello 

[Data Copying Example](https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/getting_started/data.html?highlight=data%20copying%20#data-copying)

In this example I am grasping most of the flow.

But the data copying explanation and how it affects the append list is somewhat unclear to me.

Can someone kindly explain its working, data copying? It seemed counterintuitive that no copying seemed to share all the floats, but it's obvious I've misunderstood.

> You see, the Append To List node appends the float to the original list because the Loop Input node handed it without copying (The default no-copying behavior is chosen for performance superiority.), 

Also there are two float lists in loop input node,  I understand the function of one of them (float was created by the random number list node) but not the other `floats`?

**Comment by OmarSquircleArt** [comment]
*Floats* is a parameter of type *Float List*, since we disabled it as an input in the advanced node settings, its initial value will be an empty float list. What happens is, we append/add the random float to that initially empty float list if the index of the iteration is bigger than 2.

At the first three iterations—where the index is 0, 1, 2—, the condition is False, because the index is not larger than 2. For the fourth and fifth iterations, the index is larger than 2, so we should expect the list to have the last two elements of the iterator. But this was not the case. Why? The *Append To List* node **adds an element to a list** and return the list after appending. The problem lie in the statement I marked as bold, "the node adds an element to the list", it doesn't matter if we choose to reassign it or not, the node already added the element. To fix this, we instruct Animation Nodes to give the append node a copy of the list and not the list itself, in which case, the append node will add the element to the copy and reassign that copy to the original list if and only if the index is larger than 2. Make sense?

**Comment by RodeyOrg** [comment]
> Floats is a parameter of type Float List, since we disabled it as an input in the advanced node settings, its initial value will be an empty float list. What happens is, we append/add the random float to that initially empty float list if the index of the iteration is bigger than 2.

Got it. 

> To fix this, we instruct Animation Nodes to give the append node a copy of the list and not the list itself, in which case, the append node will add the element to the copy and reassign that copy to the original list if and only if the index is larger than 2. Make sense?

Got it. I wonder if the manual language might be tweaked to reflect some of the clarification in your last reply? To emphasize exactly what data copying is passing and/or not passing to outputs? 

_Either way_ on both counts thank you.

**Comment by OmarSquircleArt** [comment]
I agree. We will look into adding such clarifications to the documentation.
