### ISSUE TITLE
Geometry Examples

### ISSUE THREAD

**Issue by RodeyOrg** [JacquesLucke/animation_nodes_manual#54]
Hello

[Geometry Nodes](https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/geometry/index.html)

I wonder if more of these might benefit from examples? Examples might be super useful for beginners. Can appreciate though it might be some work involved but even basic ones might help. 

Thanks

**Comment by OmarSquircleArt** [comment]
We omitted the examples here because we though the illustrations made the functions of the nodes clear. But sure, we will add practical examples. Thanks for your feedback.

**Comment by OmarSquircleArt** [comment]
Fixed in f76b31fbb04ad93e11bcf294958ec83b712dd1c4, b1fc600e6dbaf81ad89b5fb9149caeb1ac21e60c, 5fff3cca25ebb0712e1cdbbe8ab008d317fece5d, d489efcf7a69aab3c7b12a218a1283963b3f9775, acec909dc24d2379be592affd5726ef6c2dcb3e2, b7fdc0a181e7359a4d7c37d1469f8279788b8f7e, f3a106bb09104b076a4cf4238a078ef988b65979, and 5b68e4b5ad56ef25e0595e9559d5df2c7b7870f3.

**Comment by RodeyOrg** [comment]
Brilliant.)
