### ISSUE TITLE
Prepare Polygon Transformation

### ISSUE THREAD

**Issue by RodeyOrg** [JacquesLucke/animation_nodes_manual#65]
Hi, after many reads I haven't yet fully grasped exactly what this node does / why it's needed. Could anyone please flesh it out for me?

[PREPARE POLYGON RANSFORMATION](https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/mesh/prepare_polygon_transformation.html?highlight=preparepolygon%20transformation)

I attempted to understand it by swapping the node out with something else, and used the EXTRACT POLYGONS TRANSFORMS node, and subsequently got an ugly mess :). See below. 

![Screen Shot 2019-04-02 at 23 03 58](https://user-images.githubusercontent.com/44178760/55439165-a5b67200-559b-11e9-9b4e-8b15b678df4d.png)

**Comment by OmarSquircleArt** [comment]
That node takes your mesh, break it down to separate individual polygons and transform them such that they lie in a *Unity* setting. The *Unity* setting is such that if the polygons are transformed by the output polygon transformations, they would regain their initial settings. This is particularly useful if you want to scale/rotate some polygons around their center, in which case, you can transform the transformations you get before applying them to the *Unity* polygons, which you can see in the example provided in the documentation.

Note, however, that this node was removed in newer versions due to the introduction of the *Offset Polygons* node. So you may want to avoid it for for backward compatibility.

**Comment by RodeyOrg** [comment]
Thanks—is my following very high level understanding broadly correct?

> The node's polygons when transformed always return to their _Unity_ settings after the said transformations have taken place. 

Finally can I have _Offest Polygons_ with Blender 2.79 and this node a complete/comprehensive replacement for the _Prepare Polygon Transformation_ node i.e. can do all it does and supposedly more? 

I am currently on AN 2.0.4 and cannot see this node.

**Comment by OmarSquircleArt** [comment]
When transformed they will return to their original orientation and position. Yes, the *Offest Polygons* node can do everything that the *Prepare Polygon Transformation* can do and more.

This node was added in v2.1 at some point. So this [build](https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1_testbuilds_2) will probably have it.

**Comment by RodeyOrg** [comment]
Thanks, I've gone back to  Blender 2.79 and AN 2.0.4, it seems more stable.

I have downloaded Blender 2.80 to experiment etc

**Comment by OmarSquircleArt** [comment]
@RodeyOrg Should we close this then?

**Comment by RodeyOrg** [comment]
OK.
